// The real CommonMark-HTML conformance oracle: renders src/ast's block and inline nodes to the exact HTML string CommonMark's own reference implementation (cmark) would produce, so src/conformance.test.ts and src/gfm-conformance.test.ts can compare parseMarkdown's own output byte for byte against the vendored spec corpora's own expected `html` field.
//
// This is internal plumbing, not a public output format: readMarkdown/writeMarkdown convert between markdown and document-schema.js's ContentDocument, and never produce HTML at all -- see src/index.ts, which never re-exports anything from this module. It lives under src/html/ (built into dist/ as its own reachable subpath, per this package's `./*` export map) rather than src/test-support/ (excluded from the build entirely) because src/lower/'s own conformance-style tests reuse it too, and because it is a real, complete renderer in its own right, not a throwaway harness.
//
// Everything here is restated from cmark's own html.c rather than invented, because the corpora's expected output was generated by cmark and any difference shows up as a conformance failure that has nothing to do with parsing. Three of those restatements are load-bearing and easy to get subtly wrong:
//
//  - `cr()`. cmark emits a newline before most block elements only when the buffer does not already end in one. Reproducing that exactly, rather than joining blocks with newlines, is what makes nested containers (a list inside a block quote inside a list item) come out byte-identical.
//  - Tight lists. A paragraph inside a tight list renders as its own inline content with NO `<p>` wrapper at all; the same paragraph in a loose list gets one. The flag lives on the list, so it has to be threaded down to the paragraph two levels below.
//  - href escaping. This is NOT `encodeURI`: cmark treats every RESERVED URL character as already meaning what it says (so `?`, `=`, `&`, `#`, `/`, `:`, `;`, `,`, `%` all pass through), percent-encodes everything else byte by byte as UTF-8, and handles `&` and `'` as HTML entities rather than percent escapes since both would otherwise break the surrounding attribute.
//
// GFM task-list-item checkbox rendering (MarkdownListItemNode.checked) is a fourth restatement, sourced from the two real examples the GFM spec source itself carries (assets/gfm/spec.txt, "Task list items (extension)") -- both are TIGHT lists, so the checkbox's exact placement relative to a `<p>` wrapper in a LOOSE task-list item is not verified against a real fixture; it is rendered inside the wrapper on the same reasoning `cr()`'s own tight/loose threading already uses (the checkbox is the first fragment of the item's own first paragraph, wherever that paragraph itself renders).

import type { MarkdownBlockNode, MarkdownDocumentNode, MarkdownInlineNode, MarkdownListNode, MarkdownTableAlignment, MarkdownTableNode } from '../ast/ast';

// cmark's HREF_SAFE table: alphanumerics plus these. Every other byte -- including `"`, `<`, `>`, backtick, `\`, `[`, `]`, `^`, `{`, `|`, `}`, space, and all non-ASCII -- is percent-encoded.
const HREF_SAFE_PUNCTUATION: ReadonlySet<string> = new Set(['-', '_', '.', '+', '!', '*', '(', ')', ',', '%', '#', '@', '?', '=', ';', ':', '/', '$', '~']);
const ALPHANUMERIC_PATTERN = /^[A-Za-z0-9]$/;
const HEX_RADIX = 16;
const PERCENT_ESCAPE_DIGITS = 2;

// An ordered list renders a `start` attribute only when it does not start at the default.
const DEFAULT_ORDERED_LIST_START = 1;

export function escapeHtml(text: string): string {
  return text.replace(/[&<>"]/g, (char) => {
    switch (char) {
      case '&':
        return '&amp;';
      case '<':
        return '&lt;';
      case '>':
        return '&gt;';
      default:
        return '&quot;';
    }
  });
}

export function escapeHref(href: string): string {
  const bytes = new TextEncoder().encode(href);
  let result = '';
  for (const byte of bytes) {
    const char = String.fromCharCode(byte);
    if (byte < 0x80 && (ALPHANUMERIC_PATTERN.test(char) || HREF_SAFE_PUNCTUATION.has(char))) {
      result += char;
      continue;
    }
    if (char === '&') {
      result += '&amp;';
      continue;
    }
    if (char === "'") {
      result += '&#x27;';
      continue;
    }
    result += `%${byte.toString(HEX_RADIX).toUpperCase().padStart(PERCENT_ESCAPE_DIGITS, '0')}`;
  }
  return result;
}

function renderTitleAttribute(title: string | undefined): string {
  return title === undefined ? '' : ` title="${escapeHtml(title)}"`;
}

function renderAlignmentAttribute(alignment: MarkdownTableAlignment | undefined): string {
  return alignment === undefined || alignment === 'none' ? '' : ` align="${alignment}"`;
}

// GFM task-list checkbox markup, transcribed verbatim from the two real examples assets/gfm/spec.txt itself carries (`<input disabled="" type="checkbox">` / `<input checked="" disabled="" type="checkbox">`) -- attribute order alphabetical (checked, disabled, type), a bare boolean attribute serialised as `name=""`, and never rendered as an interactive control (every checkbox carries `disabled`, matching the spec prose: "implementors are free to render the checkboxes as disabled or immutable elements").
function renderTaskCheckbox(checked: boolean): string {
  return checked ? '<input checked="" disabled="" type="checkbox"> ' : '<input disabled="" type="checkbox"> ';
}

function renderInline(node: MarkdownInlineNode): string {
  switch (node.type) {
    case 'text':
      return escapeHtml(node.value);
    case 'entity':
      return escapeHtml(node.value);
    case 'codeSpan':
      return `<code>${escapeHtml(node.literal)}</code>`;
    case 'emphasis':
      return `<em>${renderInlines(node.children)}</em>`;
    case 'strong':
      return `<strong>${renderInlines(node.children)}</strong>`;
    case 'strikethrough':
      return `<del>${renderInlines(node.children)}</del>`;
    case 'link':
      return `<a href="${escapeHref(node.destination)}"${renderTitleAttribute(node.title)}>${renderInlines(node.children)}</a>`;
    case 'image':
      return `<img src="${escapeHref(node.destination)}" alt="${escapeHtml(node.alt)}"${renderTitleAttribute(node.title)} />`;
    case 'autolink': {
      const href = node.email ? `mailto:${node.destination}` : node.destination;
      return `<a href="${escapeHref(href)}">${escapeHtml(node.destination)}</a>`;
    }
    case 'rawHtml':
      return node.literal;
    case 'hardBreak':
      return '<br />\n';
    case 'softBreak':
      return '\n';
  }
}

export function renderInlines(nodes: readonly MarkdownInlineNode[]): string {
  return nodes.map(renderInline).join('');
}

class HtmlRenderer {
  private out = '';

  render(blocks: readonly MarkdownBlockNode[], tight: boolean): void {
    for (const block of blocks) {
      this.renderBlock(block, tight);
    }
  }

  result(): string {
    return this.out;
  }

  // cmark's own cr(): a newline before a block element, but only when the output does not already end in one.
  private cr(): void {
    if (this.out.length > 0 && !this.out.endsWith('\n')) {
      this.out += '\n';
    }
  }

  private renderBlock(node: MarkdownBlockNode, tight: boolean): void {
    switch (node.type) {
      case 'paragraph':
        if (tight) {
          this.out += renderInlines(node.children);
          return;
        }
        this.cr();
        this.out += `<p>${renderInlines(node.children)}</p>\n`;
        return;
      case 'heading':
        this.cr();
        this.out += `<h${String(node.level)}>${renderInlines(node.children)}</h${String(node.level)}>\n`;
        return;
      case 'thematicBreak':
        this.cr();
        this.out += '<hr />\n';
        return;
      case 'codeBlock':
        this.renderCodeBlock(node.infoString, node.literal);
        return;
      case 'htmlBlock':
        this.cr();
        this.out += node.literal;
        this.cr();
        return;
      case 'blockquote':
        this.cr();
        this.out += '<blockquote>\n';
        this.render(node.children, false);
        this.cr();
        this.out += '</blockquote>\n';
        return;
      case 'list':
        this.renderList(node);
        return;
      case 'table':
        this.renderTable(node);
        return;
      case 'document':
      case 'listItem':
      case 'tableRow':
      case 'tableCell':
        // Each is rendered only through its own parent, which knows the surrounding markup it needs.
        return;
    }
  }

  private renderCodeBlock(infoString: string | undefined, literal: string): void {
    this.cr();
    // cmark takes the info string's first word as the language class and ignores the rest.
    const language = infoString === undefined ? '' : (infoString.split(/[ \t]/)[0] ?? '');
    const attribute = language.length === 0 ? '' : ` class="language-${escapeHtml(language)}"`;
    this.out += `<pre><code${attribute}>${escapeHtml(literal)}</code></pre>\n`;
  }

  private renderList(node: MarkdownListNode): void {
    this.cr();
    const start = node.start ?? DEFAULT_ORDERED_LIST_START;
    const orderedOpenTag = start === DEFAULT_ORDERED_LIST_START ? '<ol>' : `<ol start="${String(start)}">`;
    this.out += `${node.markerType === 'bullet' ? '<ul>' : orderedOpenTag}\n`;
    for (const item of node.children) {
      this.cr();
      this.out += '<li>';
      // A task-list item's checkbox is the first fragment of the item's own first block -- rendered here, immediately after `<li>` and before that block's own rendering, so it lands inside a tight item's bare inline content or (unverified against a real fixture, see this module's own top-of-file note) inside a loose item's `<p>` wrapper alike.
      if (item.checked !== undefined) {
        this.out += renderTaskCheckbox(item.checked);
      }
      this.render(item.children, node.tight);
      this.out += '</li>\n';
    }
    this.out += node.markerType === 'bullet' ? '</ul>\n' : '</ol>\n';
  }

  private renderTable(node: MarkdownTableNode): void {
    this.cr();
    this.out += '<table>\n';
    const [header, ...body] = node.children;
    if (header !== undefined) {
      this.out += '<thead>\n<tr>\n';
      for (const [index, cell] of header.children.entries()) {
        this.out += `<th${renderAlignmentAttribute(node.alignments[index])}>${renderInlines(cell.children)}</th>\n`;
      }
      this.out += '</tr>\n</thead>\n';
    }
    if (body.length > 0) {
      this.out += '<tbody>\n';
      for (const row of body) {
        this.out += '<tr>\n';
        for (const [index, cell] of row.children.entries()) {
          this.out += `<td${renderAlignmentAttribute(node.alignments[index])}>${renderInlines(cell.children)}</td>\n`;
        }
        this.out += '</tr>\n';
      }
      this.out += '</tbody>\n';
    }
    this.out += '</table>\n';
  }
}

export function renderDocumentToHtml(document: MarkdownDocumentNode): string {
  const renderer = new HtmlRenderer();
  renderer.render(document.children, false);
  return renderer.result();
}
