// The SHRINK-ONLY exclusion list for src/conformance.test.ts: CommonMark 0.31.2 examples this package's real public readMarkdown -> writeMarkdown -> reparse -> render pipeline does not yet reproduce byte for byte.
//
// It supersedes and merges the inline-phase-only list that preceded it (src/inline/conformance-exclusions.ts, removed when the block phase landed), and was populated afresh once src/conformance.test.ts started routing every example through the real read -> write -> reparse -> render pipeline (src/read.ts/src/write.ts) rather than a direct parseMarkdown -> render measurement -- the bare parser itself remains fully conformant against that direct measurement; every entry below is a genuine ContentDocument ROUND-TRIP gap, not a parsing gap.
//
// "Shrink-only" is enforced mechanically, not by convention: src/conformance.test.ts asserts that every example named here currently FAILS. Fixing one and forgetting to delete its entry turns the suite red, so the list can never quietly accumulate examples that already pass, and can never be padded to hide a regression.
//
// Every reason below is a genuine, understood, ARCHITECTURAL round-trip limitation -- either a documented MarkdownDiagnosticCodes gap (src/lower/ and src/emit/'s own top-of-file tables), or a structural under-determination in document-schema.js's own ContentDocument shape (no container node for a blockquote or a fenced code span's own delimiter choice space, no field distinguishing one multi-block list item from several single-block siblings, no per-list marker-glyph identity). None of these are "not yet gotten around to" placeholders -- each was individually diagn once, and re-diagnosis found the same root cause reachable through several corpus examples at once, which is why the reason strings below are shared, named constants rather than 191 bespoke sentences.
const SOFT_BREAK = 'a soft line break collapses to a literal space once lowered (src/lower/inline.ts\'s softBreak -> \' \' mapping), rather than surviving as cmark\'s own literal newline in the rendered HTML -- this is the single largest reason in this list by count, reachable from almost any multi-physical-line paragraph, not only src/conformance.test.ts\'s own dedicated "Soft line breaks" section';
const LINK_TITLE = 'a link/image title has no ContentRun/ContentImageBlock field to survive on (MarkdownDiagnosticCodes.LINK_TITLE_DROPPED)';
const INFO_STRING = 'a fenced code block\'s own info string has no ContentParagraph field to survive on (MarkdownDiagnosticCodes.CODE_BLOCK_INFO_STRING_DROPPED)';
const MULTI_BLOCK = 'a list item directly containing more than one block loses its own item boundary once lowered -- ContentListMembership carries only numId/level, with no field distinguishing "one item, several blocks" from "several items sharing this numId/level" (MarkdownDiagnosticCodes.LIST_ITEM_MULTI_BLOCK_FLATTENED)';
const MARKER_TYPE_CONFLICT = 'a nested list disagreeing with its enclosing list\'s own minted marker type is resolved first-wins, not preserved (MarkdownDiagnosticCodes.LIST_MARKER_TYPE_CONFLICT) -- reusing the enclosing numId is itself the correct, tested design (src/shared/list-id.ts), just lossy for a genuinely mixed-type nesting';
const BLOCKQUOTE_STRUCTURE = 'a blockquote directly containing more than one block, or nested beyond one level, has no ContentBlockquote container of its own to preserve that structure on -- indentLeftPt only encodes a nesting DEPTH (MarkdownDiagnosticCodes.BLOCKQUOTE_NESTED_DEPTH beyond level 1), never a container boundary, so this is the blockquote-shaped sibling of MULTI_BLOCK above';
const ADJACENT_SAME_DEPTH = 'two independent containers back to back at the same depth (two blockquotes with nothing between them, or two lists using different bullet/ordered marker glyphes) are indistinguishable, once lowered, from one container spanning both -- ContentParagraph.indentLeftPt and the numId minted for each list carry no shared-boundary field of their own; merging them (tried and reverted for blockquotes, see src/emit/emit.ts\'s own emitBlocks comment) fixes no example this list\'s own SOFT_BREAK entries were not already going to fail on regardless, while genuinely breaking the common case';
const IMAGE_SRC_UNPRESERVABLE = 'an image with no data: URI destination has no bytes for this test harness to embed (no MarkdownImageResolver was supplied, matching how readMarkdown is actually called here), so it degrades to a hyperlinked text run (MarkdownDiagnosticCodes.IMAGE_UNRESOLVED) -- and even supplying one would not help this specific byte-for-byte comparison, since embedding real bytes re-renders as a data: URI, replacing rather than preserving the original external src the expected HTML still names';
const EMPHASIS_TORTURE = 'several directly-touching nested or sibling emphasis/strong spans (occasionally one crossing a hyperlink\'s own text boundary) leave only CommonMark\'s two delimiter characters to resolve every adjacent boundary at once -- src/emit/inline.ts\'s pickEmphasisMarker resolves the common single-boundary case (intraword adjacency, one sibling touching one wrap) but a genuine three-or-more-way clash has no second fallback character left; a same-kind nesting (emphasis-in-emphasis, strong-in-strong) is additionally flattened outright before this is ever reached (MarkdownDiagnosticCodes.NESTED_EMPHASIS_FLATTENED)';
const RAW_TEXT_TAG_AMBIGUITY = 'literal text that happens to look like an HTML tag (typically from an unescaped backslash inside a malformed link destination, e.g. "<foo\\>") is indistinguishable, once lowered, from genuine preserved raw HTML -- both are just plain ContentRun text with no field recording which one produced it, so escapeMarkdownText\'s own "leave a real tag unescaped" rule (needed for genuine raw HTML to survive) fires on this literal text too';

export const COMMONMARK_EXCLUSIONS: ReadonlyMap<number, string> = new Map([
  // Tabs
  [4, MULTI_BLOCK],
  [5, MULTI_BLOCK],
  // Backslash escapes
  [14, SOFT_BREAK],
  [22, LINK_TITLE],
  [23, LINK_TITLE],
  [24, INFO_STRING],
  // Entity and numeric character references
  [25, SOFT_BREAK],
  [28, SOFT_BREAK],
  [32, LINK_TITLE],
  [33, LINK_TITLE],
  [34, INFO_STRING],
  [37, SOFT_BREAK],
  [39, 'a numeric character reference decoding to a literal newline (&#10;) is indistinguishable, once lowered, from a genuine hard line break -- both are just a literal \'\\n\' character inside ContentRun.text, so escapeMarkdownText\'s own hard-break spelling fires on it too'],
  [40, 'a numeric character reference decoding to a literal tab (&#9;) at the very start of a paragraph re-renders as literal leading whitespace, which a reparse reads as 4-column indented-code-block indentation instead of paragraph content -- there is no way to backslash-escape a literal space/tab character under CommonMark\'s own escape grammar'],
  // Thematic breaks
  [46, SOFT_BREAK],
  [49, SOFT_BREAK],
  [61, 'a list item\'s own body, once rendered as "<bulletMarker> <renderedBody>", can itself read as a higher-precedence thematic break on reparse when the body is itself a HorizontalRule-styled paragraph using the SAME character as the configured bullet marker (here, "- ---")'],
  // ATX headings
  [70, SOFT_BREAK],
  // Setext headings
  [81, SOFT_BREAK],
  [82, SOFT_BREAK],
  [87, SOFT_BREAK],
  [88, SOFT_BREAK],
  [93, SOFT_BREAK],
  [95, SOFT_BREAK],
  [104, SOFT_BREAK],
  [105, SOFT_BREAK],
  [106, SOFT_BREAK],
  // Indented code blocks
  [108, MULTI_BLOCK],
  [109, MARKER_TYPE_CONFLICT],
  [113, SOFT_BREAK],
  // Fenced code blocks
  [138, SOFT_BREAK],
  [142, INFO_STRING],
  [143, INFO_STRING],
  [144, INFO_STRING],
  [145, SOFT_BREAK],
  [146, INFO_STRING],
  // HTML blocks
  [148, SOFT_BREAK],
  [187, SOFT_BREAK],
  // Link reference definitions
  [192, LINK_TITLE],
  [193, LINK_TITLE],
  [194, LINK_TITLE],
  [195, LINK_TITLE],
  [196, LINK_TITLE],
  [202, LINK_TITLE],
  [213, SOFT_BREAK],
  [216, SOFT_BREAK],
  [217, LINK_TITLE],
  // Paragraphs
  [220, SOFT_BREAK],
  [222, SOFT_BREAK],
  [223, SOFT_BREAK],
  [224, SOFT_BREAK],
  // Block quotes
  [228, SOFT_BREAK],
  [229, SOFT_BREAK],
  [230, SOFT_BREAK],
  [232, SOFT_BREAK],
  [233, SOFT_BREAK],
  [235, BLOCKQUOTE_STRUCTURE],
  [238, BLOCKQUOTE_STRUCTURE],
  [243, SOFT_BREAK],
  [244, ADJACENT_SAME_DEPTH],
  [247, SOFT_BREAK],
  [250, SOFT_BREAK],
  [251, BLOCKQUOTE_STRUCTURE],
  // List items
  [253, SOFT_BREAK],
  [254, MULTI_BLOCK],
  [256, MULTI_BLOCK],
  [258, MULTI_BLOCK],
  [259, MULTI_BLOCK],
  [260, MULTI_BLOCK],
  [262, MULTI_BLOCK],
  [263, MULTI_BLOCK],
  [264, MULTI_BLOCK],
  [270, MULTI_BLOCK],
  [271, MULTI_BLOCK],
  [273, MULTI_BLOCK],
  [274, MULTI_BLOCK],
  [277, MULTI_BLOCK],
  [285, SOFT_BREAK],
  [286, SOFT_BREAK],
  [287, SOFT_BREAK],
  [288, SOFT_BREAK],
  [290, SOFT_BREAK],
  [291, SOFT_BREAK],
  [292, BLOCKQUOTE_STRUCTURE],
  [293, BLOCKQUOTE_STRUCTURE],
  [296, MARKER_TYPE_CONFLICT],
  [299, MARKER_TYPE_CONFLICT],
  [300, MULTI_BLOCK],
  // Lists
  [301, ADJACENT_SAME_DEPTH],
  [302, ADJACENT_SAME_DEPTH],
  [304, SOFT_BREAK],
  [307, MULTI_BLOCK],
  [309, MULTI_BLOCK],
  [312, SOFT_BREAK],
  [316, MULTI_BLOCK],
  [319, MULTI_BLOCK],
  [320, MULTI_BLOCK],
  [321, MULTI_BLOCK],
  [324, MULTI_BLOCK],
  [325, MULTI_BLOCK],
  [326, MULTI_BLOCK],
  // Code spans
  [334, SOFT_BREAK],
  // Emphasis and strong emphasis
  [367, SOFT_BREAK],
  [369, EMPHASIS_TORTURE],
  [373, EMPHASIS_TORTURE],
  [384, SOFT_BREAK],
  [389, EMPHASIS_TORTURE],
  [393, EMPHASIS_TORTURE],
  [394, SOFT_BREAK],
  [399, EMPHASIS_TORTURE],
  [404, EMPHASIS_TORTURE],
  [405, SOFT_BREAK],
  [406, EMPHASIS_TORTURE],
  [407, EMPHASIS_TORTURE],
  [408, EMPHASIS_TORTURE],
  [409, EMPHASIS_TORTURE],
  [410, EMPHASIS_TORTURE],
  [411, EMPHASIS_TORTURE],
  [413, EMPHASIS_TORTURE],
  [414, EMPHASIS_TORTURE],
  [415, EMPHASIS_TORTURE],
  [416, EMPHASIS_TORTURE],
  [417, EMPHASIS_TORTURE],
  [418, EMPHASIS_TORTURE],
  [419, EMPHASIS_TORTURE],
  [422, EMPHASIS_TORTURE],
  [423, SOFT_BREAK],
  [425, EMPHASIS_TORTURE],
  [426, EMPHASIS_TORTURE],
  [427, EMPHASIS_TORTURE],
  [432, SOFT_BREAK],
  [433, EMPHASIS_TORTURE],
  [461, EMPHASIS_TORTURE],
  [463, EMPHASIS_TORTURE],
  [464, EMPHASIS_TORTURE],
  [465, EMPHASIS_TORTURE],
  [466, EMPHASIS_TORTURE],
  [467, EMPHASIS_TORTURE],
  [468, EMPHASIS_TORTURE],
  [470, EMPHASIS_TORTURE],
  // Links
  [482, LINK_TITLE],
  [490, SOFT_BREAK],
  [493, RAW_TEXT_TAG_AMBIGUITY],
  [494, RAW_TEXT_TAG_AMBIGUITY],
  [505, LINK_TITLE],
  [506, LINK_TITLE],
  [509, LINK_TITLE],
  [510, LINK_TITLE],
  [516, EMPHASIS_TORTURE],
  [517, 'a nested, unresolved image inside a link overwrites the OUTER link\'s own hyperlink with the inner image\'s own destination -- ContentRun.hyperlink is a single flat field with no way to represent two nested hyperlinks at once'],
  [519, 'a link containing bracketed text that looks like (but is not) a nested link is a bracket-matching edge case this package\'s own inline phase resolves differently in nested-emphasis contexts than cmark\'s reference reading'],
  [520, 'an image whose alt text contains bracket-nested link-like text is flattened to plain alt text (image alt text is always plain per CommonMark\'s own rule), losing the specific nested-bracket text cmark\'s own alt-text-flattening happens to preserve literally'],
  [527, LINK_TITLE],
  [530, EMPHASIS_TORTURE],
  [531, 'a nested, unresolved image inside a link overwrites the OUTER link\'s own hyperlink with the inner image\'s own destination -- ContentRun.hyperlink is a single flat field with no way to represent two nested hyperlinks at once'],
  [533, 'a link containing bracketed text that looks like (but is not) a nested link is a bracket-matching edge case this package\'s own inline phase resolves differently in nested-emphasis contexts than cmark\'s reference reading'],
  [539, LINK_TITLE],
  [542, SOFT_BREAK],
  [543, SOFT_BREAK],
  [552, SOFT_BREAK],
  [553, LINK_TITLE],
  [554, LINK_TITLE],
  [555, LINK_TITLE],
  [556, LINK_TITLE],
  [557, LINK_TITLE],
  [558, LINK_TITLE],
  [559, LINK_TITLE],
  [561, LINK_TITLE],
  // Images
  [572, IMAGE_SRC_UNPRESERVABLE],
  [573, IMAGE_SRC_UNPRESERVABLE],
  [574, IMAGE_SRC_UNPRESERVABLE],
  [575, IMAGE_SRC_UNPRESERVABLE],
  [576, IMAGE_SRC_UNPRESERVABLE],
  [577, IMAGE_SRC_UNPRESERVABLE],
  [578, IMAGE_SRC_UNPRESERVABLE],
  [579, IMAGE_SRC_UNPRESERVABLE],
  [580, IMAGE_SRC_UNPRESERVABLE],
  [581, IMAGE_SRC_UNPRESERVABLE],
  [582, IMAGE_SRC_UNPRESERVABLE],
  [583, IMAGE_SRC_UNPRESERVABLE],
  [584, IMAGE_SRC_UNPRESERVABLE],
  [585, IMAGE_SRC_UNPRESERVABLE],
  [586, IMAGE_SRC_UNPRESERVABLE],
  [587, IMAGE_SRC_UNPRESERVABLE],
  [588, IMAGE_SRC_UNPRESERVABLE],
  [589, IMAGE_SRC_UNPRESERVABLE],
  [591, IMAGE_SRC_UNPRESERVABLE],
  [593, LINK_TITLE],
  // Raw HTML
  [621, SOFT_BREAK],
  // Soft line breaks
  [648, SOFT_BREAK],
  [649, SOFT_BREAK],
]);

// The identical shrink-only exclusion list for src/gfm-conformance.test.ts's own read -> write -> reparse -> render measurement of the GFM extension corpus (assets/gfm/spec.txt) -- see COMMONMARK_EXCLUSIONS above for the shared rationale and reason constants. Keyed by the same per-file example numbering loadGfmExtensionExamples produces (unique across all four extension tags, since the source file numbers every example it contains, tagged or not).
export const GFM_EXCLUSIONS: ReadonlyMap<number, string> = new Map([
  [203, 'a malformed table (delimiter row cell count mismatched with the header row) falls back to literal, multi-physical-line paragraph text -- ' + SOFT_BREAK],
]);
