// A minimal HTML renderer over src/ast's inline nodes, existing solely so the inline phase can be compared against the CommonMark conformance corpus's own `html` field. It is NOT a public output format of this package -- readMarkdown/writeMarkdown convert between markdown and document-schema.js's ContentDocument, and never produce HTML.
//
// The two escaping functions below are restated from cmark's own houdini_escape_html0/houdini_escape_href, because the corpus's expected output was generated by cmark and any difference in escaping shows up as a conformance failure that has nothing to do with parsing. In particular the href escaping is NOT `encodeURI`: cmark treats every RESERVED URL character as already meaning what it says (so `?`, `=`, `&`, `#`, `/`, `:`, `;`, `,`, `%` all pass through), percent-encodes everything else byte by byte as UTF-8, and handles `&` and `'` as HTML entities rather than percent escapes since both would otherwise break the surrounding attribute.

import type { MarkdownDocumentNode, MarkdownInlineNode } from '../ast/ast';

// cmark's HREF_SAFE table: alphanumerics plus these. Every other byte -- including `"`, `<`, `>`, backtick, `\`, `[`, `]`, `^`, `{`, `|`, `}`, space, and all non-ASCII -- is percent-encoded.
const HREF_SAFE_PUNCTUATION: ReadonlySet<string> = new Set(['-', '_', '.', '+', '!', '*', '(', ')', ',', '%', '#', '@', '?', '=', ';', ':', '/', '$', '~']);
const ALPHANUMERIC_PATTERN = /^[A-Za-z0-9]$/;
const HEX_RADIX = 16;
const PERCENT_ESCAPE_DIGITS = 2;

export function escapeHtml(text: string): string {
  return text.replace(/[&<>"]/g, (char) => {
    switch (char) {
      case '&':
        return '&amp;';
      case '<':
        return '&lt;';
      case '>':
        return '&gt;';
      default:
        return '&quot;';
    }
  });
}

export function escapeHref(href: string): string {
  const bytes = new TextEncoder().encode(href);
  let result = '';
  for (const byte of bytes) {
    const char = String.fromCharCode(byte);
    if (byte < 0x80 && (ALPHANUMERIC_PATTERN.test(char) || HREF_SAFE_PUNCTUATION.has(char))) {
      result += char;
      continue;
    }
    if (char === '&') {
      result += '&amp;';
      continue;
    }
    if (char === "'") {
      result += '&#x27;';
      continue;
    }
    result += `%${byte.toString(HEX_RADIX).toUpperCase().padStart(PERCENT_ESCAPE_DIGITS, '0')}`;
  }
  return result;
}

function renderTitleAttribute(title: string | undefined): string {
  return title === undefined ? '' : ` title="${escapeHtml(title)}"`;
}

function renderInline(node: MarkdownInlineNode): string {
  switch (node.type) {
    case 'text':
      return escapeHtml(node.value);
    case 'entity':
      return escapeHtml(node.value);
    case 'codeSpan':
      return `<code>${escapeHtml(node.literal)}</code>`;
    case 'emphasis':
      return `<em>${renderInlines(node.children)}</em>`;
    case 'strong':
      return `<strong>${renderInlines(node.children)}</strong>`;
    case 'strikethrough':
      return `<del>${renderInlines(node.children)}</del>`;
    case 'link':
      return `<a href="${escapeHref(node.destination)}"${renderTitleAttribute(node.title)}>${renderInlines(node.children)}</a>`;
    case 'image':
      return `<img src="${escapeHref(node.destination)}" alt="${escapeHtml(node.alt)}"${renderTitleAttribute(node.title)} />`;
    case 'autolink': {
      const href = node.email ? `mailto:${node.destination}` : node.destination;
      return `<a href="${escapeHref(href)}">${escapeHtml(node.destination)}</a>`;
    }
    case 'rawHtml':
      return node.literal;
    case 'hardBreak':
      return '<br />\n';
    case 'softBreak':
      return '\n';
  }
}

export function renderInlines(nodes: readonly MarkdownInlineNode[]): string {
  return nodes.map(renderInline).join('');
}

// Renders only what src/test-support/parse-markdown.ts can produce -- a document of paragraphs. The real block phase's own node kinds will need their own renderer when they exist.
export function renderDocumentToHtml(document: MarkdownDocumentNode): string {
  return document.children
    .map((block) => (block.type === 'paragraph' ? `<p>${renderInlines(block.children)}</p>\n` : ''))
    .join('');
}
